USE [master]
GO
/****** Object:  Database [QUANLY_KHUTRO]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE DATABASE QUANLY_KHUTRO;
GO
ALTER DATABASE [QUANLY_KHUTRO] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QUANLY_KHUTRO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QUANLY_KHUTRO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET ARITHABORT OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET  MULTI_USER 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QUANLY_KHUTRO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QUANLY_KHUTRO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QUANLY_KHUTRO] SET QUERY_STORE = ON
GO
ALTER DATABASE [QUANLY_KHUTRO] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QUANLY_KHUTRO]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACCOUNT]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[IDUser] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Passwords] [varchar](255) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Phone] [varchar](15) NOT NULL,
	[Email] [varchar](100) NULL,
	[Avatar] [varchar](255) NULL,
	[Roles] [varchar](10) NOT NULL,
	[QR_Link] [varchar](255) NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
	[ExtraRoles] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIG_GIA]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIG_GIA](
	[IDConfig] [int] IDENTITY(1,1) NOT NULL,
	[TenDichVu] [nvarchar](50) NOT NULL,
	[MaDichVu] [varchar](30) NOT NULL,
	[DonGia] [decimal](15, 2) NOT NULL,
	[DonVi] [nvarchar](20) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[NgayApDung] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDConfig] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MaDichVu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIENNUOC]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIENNUOC](
	[IDGhiNhan] [int] IDENTITY(1,1) NOT NULL,
	[IDPhong] [int] NOT NULL,
	[KyGhiNhan] [varchar](7) NOT NULL,
	[SoDienMoi] [int] NOT NULL,
	[SoNuocMoi] [int] NOT NULL,
	[SoDienCu] [int] NOT NULL,
	[SoNuocCu] [int] NOT NULL,
	[AnhChupDongHo] [varchar](255) NOT NULL,
	[TrangThaiDuyet] [tinyint] NOT NULL,
	[IDManagerDuyet] [int] NULL,
	[NgayDuyet] [datetime2](7) NULL,
	[GhiChuDuyet] [nvarchar](200) NULL,
	[NgayGhi] [datetime2](7) NOT NULL,
	[AnhChupDongHoNuoc] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDGhiNhan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_DIENNUOC_Phong_Ky] UNIQUE NONCLUSTERED 
(
	[IDPhong] ASC,
	[KyGhiNhan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DONDV]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONDV](
	[IDDonDV] [int] IDENTITY(1,1) NOT NULL,
	[IDUser] [int] NOT NULL,
	[IDPhong] [int] NOT NULL,
	[IDManagerXuLy] [int] NULL,
	[LoaiDV] [nvarchar](30) NOT NULL,
	[NoiDung] [nvarchar](500) NULL,
	[MucDo] [nvarchar](20) NOT NULL,
	[TongTien] [decimal](15, 2) NOT NULL,
	[TrangThai_DV] [nvarchar](30) NOT NULL,
	[LyDoHuy] [nvarchar](200) NULL,
	[NguoiHuy] [varchar](10) NULL,
	[AnhBienLai] [varchar](255) NULL,
	[AnhKetQua] [varchar](255) NULL,
	[GhiChuXuLy] [nvarchar](500) NULL,
	[NgayXuLy] [datetime2](7) NULL,
	[NgayHoanThanh] [datetime2](7) NULL,
	[NgayTao] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
	[NgayHetHan] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDDonDV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HDTHANG]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HDTHANG](
	[IDHDThang] [int] IDENTITY(1,1) NOT NULL,
	[IDPhong] [int] NOT NULL,
	[IDDienNuoc] [int] NULL,
	[IDManagerDuyet] [int] NULL,
	[KyThanhToan] [varchar](7) NOT NULL,
	[TienPhong] [decimal](15, 2) NOT NULL,
	[TienDienSum] [decimal](15, 2) NOT NULL,
	[TienNuocSum] [decimal](15, 2) NOT NULL,
	[TienDV] [decimal](15, 2) NOT NULL,
	[TongCong] [decimal](15, 2) NOT NULL,
	[HanDong] [date] NOT NULL,
	[TrangThai_TT] [nvarchar](20) NOT NULL,
	[AnhChuyenKhoan] [varchar](255) NULL,
	[NgayDuyet] [datetime2](7) NULL,
	[GhiChuDuyet] [nvarchar](200) NULL,
	[NgayXuatHD] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
	[TienNoDV] [decimal](15, 2) NULL,
	[NgayHetHan] [datetime2](7) NULL,
	[DuocCongVaoTro] [bit] NOT NULL,
	[DaCoNhacNo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDHDThang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_HDTHANG_Phong_Ky] UNIQUE NONCLUSTERED 
(
	[IDPhong] ASC,
	[KyThanhToan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOPDONG]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOPDONG](
	[IDHopDong] [int] IDENTITY(1,1) NOT NULL,
	[IDUser] [int] NOT NULL,
	[IDPhong] [int] NOT NULL,
	[IDManager] [int] NULL,
	[NgayBatDau] [date] NOT NULL,
	[NgayKetThuc] [date] NULL,
	[DienDauKy] [int] NOT NULL,
	[NuocDauKy] [int] NOT NULL,
	[TienCocBanDau] [decimal](15, 2) NOT NULL,
	[TrangThaiHD] [nvarchar](20) NOT NULL,
	[GhiChu] [nvarchar](500) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
	[GiaThueChot] [decimal](15, 2) NOT NULL,
	[NgayThanhLy] [date] NULL,
	[TienCocHoanTra] [decimal](15, 2) NULL,
	[LyDoKetThuc] [nvarchar](500) NULL,
	[IDManagerThanhLy] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDHopDong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOPDONG_DICHVU]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOPDONG_DICHVU](
	[IDHDDichVu] [int] IDENTITY(1,1) NOT NULL,
	[IDHopDong] [int] NOT NULL,
	[MaDichVu] [varchar](30) NOT NULL,
	[TenDichVu] [nvarchar](50) NOT NULL,
	[DonGiaChot] [decimal](15, 2) NOT NULL,
	[DonVi] [nvarchar](20) NOT NULL,
	[SoLuong] [int] NOT NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
	[NgayDangKy] [date] NOT NULL,
	[NgayHuy] [date] NULL,
	[GhiChu] [nvarchar](200) NULL,
 CONSTRAINT [PK_HOPDONG_DICHVU] PRIMARY KEY CLUSTERED 
(
	[IDHDDichVu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_HDDV_HopDong_DichVu_Active] UNIQUE NONCLUSTERED 
(
	[IDHopDong] ASC,
	[MaDichVu] ASC,
	[TrangThai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOPDONG_KHACHO]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOPDONG_KHACHO](
	[IDKhachO] [int] IDENTITY(1,1) NOT NULL,
	[IDHopDong] [int] NOT NULL,
	[IDUser] [int] NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[SoCCCD] [varchar](15) NULL,
	[NgaySinh] [date] NULL,
	[GioiTinh] [nvarchar](10) NULL,
	[SoDienThoai] [varchar](15) NULL,
	[QuanHe] [nvarchar](50) NULL,
	[IsChinhChu] [bit] NOT NULL,
	[NgayVao] [date] NOT NULL,
	[NgayRa] [date] NULL,
	[GhiChu] [nvarchar](200) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_HOPDONG_KHACHO] PRIMARY KEY CLUSTERED 
(
	[IDKhachO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_KHACHO_HopDong_CCCD] UNIQUE NONCLUSTERED 
(
	[IDHopDong] ASC,
	[SoCCCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACH_THUE]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_THUE](
	[IDKhachThue] [int] IDENTITY(1,1) NOT NULL,
	[IDUser] [int] NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[SoCCCD] [varchar](15) NOT NULL,
	[NgaySinh] [date] NULL,
	[GioiTinh] [nvarchar](10) NULL,
	[SoDienThoai] [varchar](15) NULL,
	[QueQuan] [nvarchar](100) NULL,
	[AnhChanDung] [nvarchar](max) NULL,
	[NgayVaoO] [date] NULL,
	[GhiChu] [nvarchar](max) NULL,
	[DiaChiThuongTru] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDKhachThue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SoCCCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[IDUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHONG]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHONG](
	[IDPhong] [int] IDENTITY(1,1) NOT NULL,
	[SoPhong] [varchar](10) NOT NULL,
	[Khu] [tinyint] NOT NULL,
	[DienTich] [decimal](6, 2) NULL,
	[GiaPhongFix] [decimal](15, 2) NOT NULL,
	[MoTa] [nvarchar](500) NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[soluong] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SoPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHONG_MANAGER]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHONG_MANAGER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDPhong] [int] NOT NULL,
	[IDManager] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[GhiChu] [nvarchar](200) NULL,
	[NgayPhanCong] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_PHONG_MANAGER_ACTIVE] UNIQUE NONCLUSTERED 
(
	[IDPhong] ASC,
	[IDManager] ASC,
	[IsActive] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THONGBAO]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THONGBAO](
	[IDThongBao] [int] IDENTITY(1,1) NOT NULL,
	[IDNguoiGui] [int] NULL,
	[IDUser] [int] NULL,
	[IDNguonTB] [int] NULL,
	[LoaiNguon] [varchar](20) NULL,
	[TieuDe] [nvarchar](200) NOT NULL,
	[NoiDung] [nvarchar](500) NULL,
	[LoaiTB] [nvarchar](20) NOT NULL,
	[DaDoc] [bit] NOT NULL,
	[NgayTao] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDThongBao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THONGKE_DOANHTHU_THANG]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THONGKE_DOANHTHU_THANG](
	[IDThongKe] [int] IDENTITY(1,1) NOT NULL,
	[Nam] [smallint] NOT NULL,
	[Thang] [tinyint] NOT NULL,
	[TongTienPhong] [decimal](15, 2) NOT NULL,
	[TongTienDien] [decimal](15, 2) NOT NULL,
	[TongTienNuoc] [decimal](15, 2) NOT NULL,
	[TongTienDV] [decimal](15, 2) NOT NULL,
	[TongCong] [decimal](15, 2) NOT NULL,
	[SoHoaDonDaDong] [int] NOT NULL,
	[NgayCapNhat] [datetime2](7) NOT NULL,
	[ChiPhiThang] [decimal](15, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDThongKe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_NAM_THANG] UNIQUE NONCLUSTERED 
(
	[Nam] ASC,
	[Thang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THONGKE_TONG]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THONGKE_TONG](
	[ID] [int] NOT NULL,
	[TongSoPhong] [int] NOT NULL,
	[PhongDangThue] [int] NOT NULL,
	[PhongConTrong] [int] NOT NULL,
	[PhongDangSua] [int] NOT NULL,
	[TiLeLapDay] [decimal](5, 2) NOT NULL,
	[DoanhThuThangNay] [decimal](15, 2) NOT NULL,
	[DoanhThuThangTruoc] [decimal](15, 2) NOT NULL,
	[TangTruongDoanhThu] [decimal](5, 2) NOT NULL,
	[HoaDonChuaDong] [int] NOT NULL,
	[HoaDonSapDenHan] [int] NOT NULL,
	[HoaDonQuaHan] [int] NOT NULL,
	[DonDVChoXuLy] [int] NOT NULL,
	[DonDVKhanCap] [int] NOT NULL,
	[NgayCapNhat] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_THONGKE_TONG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_ACCOUNT_IsActive]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_ACCOUNT_IsActive] ON [dbo].[ACCOUNT]
(
	[IsActive] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_ACCOUNT_Roles]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_ACCOUNT_Roles] ON [dbo].[ACCOUNT]
(
	[Roles] ASC
)
WHERE ([IsActive]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_CONFIG_MaDV]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_CONFIG_MaDV] ON [dbo].[CONFIG_GIA]
(
	[MaDichVu] ASC
)
WHERE ([IsActive]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DIENNUOC_Duyet]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DIENNUOC_Duyet] ON [dbo].[DIENNUOC]
(
	[TrangThaiDuyet] ASC
)
WHERE ([TrangThaiDuyet]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_DIENNUOC_Phong_Ky]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DIENNUOC_Phong_Ky] ON [dbo].[DIENNUOC]
(
	[IDPhong] ASC,
	[KyGhiNhan] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DONDV_IDManager]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DONDV_IDManager] ON [dbo].[DONDV]
(
	[IDManagerXuLy] ASC
)
WHERE ([IDManagerXuLy] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DONDV_IDPhong]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DONDV_IDPhong] ON [dbo].[DONDV]
(
	[IDPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DONDV_IDUser]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DONDV_IDUser] ON [dbo].[DONDV]
(
	[IDUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_DONDV_LoaiDV]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DONDV_LoaiDV] ON [dbo].[DONDV]
(
	[LoaiDV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_DONDV_Phong_Trang]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DONDV_Phong_Trang] ON [dbo].[DONDV]
(
	[IDPhong] ASC,
	[TrangThai_DV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_DONDV_TrangThai]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DONDV_TrangThai] ON [dbo].[DONDV]
(
	[TrangThai_DV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HDTHANG_IDManager]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HDTHANG_IDManager] ON [dbo].[HDTHANG]
(
	[IDManagerDuyet] ASC
)
WHERE ([IDManagerDuyet] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_HDTHANG_Ky_Trang]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HDTHANG_Ky_Trang] ON [dbo].[HDTHANG]
(
	[KyThanhToan] ASC,
	[TrangThai_TT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_HDTHANG_Phong_Ky]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HDTHANG_Phong_Ky] ON [dbo].[HDTHANG]
(
	[IDPhong] ASC,
	[KyThanhToan] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_HDTHANG_TrangThai]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HDTHANG_TrangThai] ON [dbo].[HDTHANG]
(
	[TrangThai_TT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HOPDONG_IDManager]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HOPDONG_IDManager] ON [dbo].[HOPDONG]
(
	[IDManager] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HOPDONG_IDPhong]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HOPDONG_IDPhong] ON [dbo].[HOPDONG]
(
	[IDPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HOPDONG_IDUser]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HOPDONG_IDUser] ON [dbo].[HOPDONG]
(
	[IDUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_HOPDONG_TrangThai]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HOPDONG_TrangThai] ON [dbo].[HOPDONG]
(
	[TrangThaiHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_HDDV_HopDong_Active]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_HDDV_HopDong_Active] ON [dbo].[HOPDONG_DICHVU]
(
	[IDHopDong] ASC,
	[TrangThai] ASC
)
INCLUDE([MaDichVu],[DonGiaChot],[SoLuong]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_KHACHO_HopDong]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_KHACHO_HopDong] ON [dbo].[HOPDONG_KHACHO]
(
	[IDHopDong] ASC
)
INCLUDE([HoTen],[SoCCCD],[IsChinhChu],[NgayRa]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ_KHACHO_ChinhChu]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE UNIQUE NONCLUSTERED INDEX [UQ_KHACHO_ChinhChu] ON [dbo].[HOPDONG_KHACHO]
(
	[IDHopDong] ASC
)
WHERE ([IsChinhChu]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_PHONG_TrangThai]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_PHONG_TrangThai] ON [dbo].[PHONG]
(
	[TrangThai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PM_IDManager]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_PM_IDManager] ON [dbo].[PHONG_MANAGER]
(
	[IDManager] ASC
)
WHERE ([IsActive]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PM_IDPhong]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_PM_IDPhong] ON [dbo].[PHONG_MANAGER]
(
	[IDPhong] ASC
)
WHERE ([IsActive]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_THONGBAO_NgayTao]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_THONGBAO_NgayTao] ON [dbo].[THONGBAO]
(
	[NgayTao] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_THONGBAO_User_Doc]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_THONGBAO_User_Doc] ON [dbo].[THONGBAO]
(
	[IDUser] ASC,
	[DaDoc] ASC
)
WHERE ([DaDoc]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DOANHTHU_Nam]    Script Date: 01/06/2026 10:59:04 SA ******/
CREATE NONCLUSTERED INDEX [IX_DOANHTHU_Nam] ON [dbo].[THONGKE_DOANHTHU_THANG]
(
	[Nam] ASC,
	[Thang] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNT] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[ACCOUNT] ADD  DEFAULT (getutcdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[ACCOUNT] ADD  DEFAULT (getutcdate()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[CONFIG_GIA] ADD  DEFAULT (N'lần') FOR [DonVi]
GO
ALTER TABLE [dbo].[CONFIG_GIA] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[CONFIG_GIA] ADD  DEFAULT (getutcdate()) FOR [NgayApDung]
GO
ALTER TABLE [dbo].[DIENNUOC] ADD  DEFAULT ((0)) FOR [TrangThaiDuyet]
GO
ALTER TABLE [dbo].[DIENNUOC] ADD  DEFAULT (getutcdate()) FOR [NgayGhi]
GO
ALTER TABLE [dbo].[DONDV] ADD  DEFAULT (N'Trung bình') FOR [MucDo]
GO
ALTER TABLE [dbo].[DONDV] ADD  DEFAULT ((0)) FOR [TongTien]
GO
ALTER TABLE [dbo].[DONDV] ADD  DEFAULT (N'Chờ xử lý') FOR [TrangThai_DV]
GO
ALTER TABLE [dbo].[DONDV] ADD  DEFAULT (getutcdate()) FOR [NgayTao]
GO
ALTER TABLE [dbo].[DONDV] ADD  DEFAULT (getutcdate()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[HDTHANG] ADD  DEFAULT ((0.0)) FOR [TienDV]
GO
ALTER TABLE [dbo].[HDTHANG] ADD  DEFAULT (N'Chưa đóng') FOR [TrangThai_TT]
GO
ALTER TABLE [dbo].[HDTHANG] ADD  DEFAULT (getutcdate()) FOR [NgayXuatHD]
GO
ALTER TABLE [dbo].[HDTHANG] ADD  DEFAULT (getutcdate()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[HDTHANG] ADD  DEFAULT (CONVERT([bit],(0))) FOR [DuocCongVaoTro]
GO
ALTER TABLE [dbo].[HDTHANG] ADD  DEFAULT (CONVERT([bit],(0))) FOR [DaCoNhacNo]
GO
ALTER TABLE [dbo].[HOPDONG] ADD  DEFAULT ((0)) FOR [DienDauKy]
GO
ALTER TABLE [dbo].[HOPDONG] ADD  DEFAULT ((0)) FOR [NuocDauKy]
GO
ALTER TABLE [dbo].[HOPDONG] ADD  DEFAULT ((0)) FOR [TienCocBanDau]
GO
ALTER TABLE [dbo].[HOPDONG] ADD  DEFAULT (N'Đang hiệu lực') FOR [TrangThaiHD]
GO
ALTER TABLE [dbo].[HOPDONG] ADD  DEFAULT (getutcdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[HOPDONG] ADD  DEFAULT (getutcdate()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[HOPDONG] ADD  CONSTRAINT [DF_HOPDONG_GiaThueChot]  DEFAULT ((0)) FOR [GiaThueChot]
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU] ADD  CONSTRAINT [DF_HDDV_SoLuong]  DEFAULT ((1)) FOR [SoLuong]
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU] ADD  CONSTRAINT [DF_HDDV_TrangThai]  DEFAULT (N'Đang dùng') FOR [TrangThai]
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU] ADD  CONSTRAINT [DF_HDDV_NgayDangKy]  DEFAULT (CONVERT([date],getdate())) FOR [NgayDangKy]
GO
ALTER TABLE [dbo].[HOPDONG_KHACHO] ADD  CONSTRAINT [DF_KHACHO_IsChinhChu]  DEFAULT ((0)) FOR [IsChinhChu]
GO
ALTER TABLE [dbo].[HOPDONG_KHACHO] ADD  CONSTRAINT [DF_KHACHO_NgayVao]  DEFAULT (CONVERT([date],getdate())) FOR [NgayVao]
GO
ALTER TABLE [dbo].[HOPDONG_KHACHO] ADD  CONSTRAINT [DF_KHACHO_CreatedAt]  DEFAULT (getutcdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[KHACH_THUE] ADD  DEFAULT (getdate()) FOR [NgayVaoO]
GO
ALTER TABLE [dbo].[PHONG] ADD  DEFAULT ((1)) FOR [Khu]
GO
ALTER TABLE [dbo].[PHONG] ADD  DEFAULT (N'Trống') FOR [TrangThai]
GO
ALTER TABLE [dbo].[PHONG] ADD  DEFAULT (getutcdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[PHONG_MANAGER] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[PHONG_MANAGER] ADD  DEFAULT (getutcdate()) FOR [NgayPhanCong]
GO
ALTER TABLE [dbo].[THONGBAO] ADD  DEFAULT (N'thong-tin') FOR [LoaiTB]
GO
ALTER TABLE [dbo].[THONGBAO] ADD  DEFAULT ((0)) FOR [DaDoc]
GO
ALTER TABLE [dbo].[THONGBAO] ADD  DEFAULT (getutcdate()) FOR [NgayTao]
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG] ADD  DEFAULT ((0)) FOR [TongTienPhong]
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG] ADD  DEFAULT ((0)) FOR [TongTienDien]
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG] ADD  DEFAULT ((0)) FOR [TongTienNuoc]
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG] ADD  DEFAULT ((0)) FOR [TongTienDV]
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG] ADD  DEFAULT ((0)) FOR [TongCong]
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG] ADD  DEFAULT ((0)) FOR [SoHoaDonDaDong]
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG] ADD  DEFAULT (getutcdate()) FOR [NgayCapNhat]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((1)) FOR [ID]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [TongSoPhong]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [PhongDangThue]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [PhongConTrong]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [PhongDangSua]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [TiLeLapDay]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [DoanhThuThangNay]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [DoanhThuThangTruoc]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [TangTruongDoanhThu]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [HoaDonChuaDong]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [HoaDonSapDenHan]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [HoaDonQuaHan]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [DonDVChoXuLy]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT ((0)) FOR [DonDVKhanCap]
GO
ALTER TABLE [dbo].[THONGKE_TONG] ADD  DEFAULT (getutcdate()) FOR [NgayCapNhat]
GO
ALTER TABLE [dbo].[DIENNUOC]  WITH CHECK ADD FOREIGN KEY([IDManagerDuyet])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[DIENNUOC]  WITH CHECK ADD FOREIGN KEY([IDPhong])
REFERENCES [dbo].[PHONG] ([IDPhong])
GO
ALTER TABLE [dbo].[DONDV]  WITH CHECK ADD FOREIGN KEY([IDManagerXuLy])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[DONDV]  WITH CHECK ADD FOREIGN KEY([IDPhong])
REFERENCES [dbo].[PHONG] ([IDPhong])
GO
ALTER TABLE [dbo].[DONDV]  WITH CHECK ADD FOREIGN KEY([IDUser])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[HDTHANG]  WITH CHECK ADD FOREIGN KEY([IDDienNuoc])
REFERENCES [dbo].[DIENNUOC] ([IDGhiNhan])
GO
ALTER TABLE [dbo].[HDTHANG]  WITH CHECK ADD FOREIGN KEY([IDManagerDuyet])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[HDTHANG]  WITH CHECK ADD FOREIGN KEY([IDPhong])
REFERENCES [dbo].[PHONG] ([IDPhong])
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD FOREIGN KEY([IDManager])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD FOREIGN KEY([IDPhong])
REFERENCES [dbo].[PHONG] ([IDPhong])
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD FOREIGN KEY([IDUser])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD  CONSTRAINT [FK_HOPDONG_ManagerThanhLy] FOREIGN KEY([IDManagerThanhLy])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[HOPDONG] CHECK CONSTRAINT [FK_HOPDONG_ManagerThanhLy]
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU]  WITH CHECK ADD  CONSTRAINT [FK_HDDV_ConfigGia] FOREIGN KEY([MaDichVu])
REFERENCES [dbo].[CONFIG_GIA] ([MaDichVu])
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU] CHECK CONSTRAINT [FK_HDDV_ConfigGia]
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU]  WITH CHECK ADD  CONSTRAINT [FK_HDDV_HopDong] FOREIGN KEY([IDHopDong])
REFERENCES [dbo].[HOPDONG] ([IDHopDong])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU] CHECK CONSTRAINT [FK_HDDV_HopDong]
GO
ALTER TABLE [dbo].[HOPDONG_KHACHO]  WITH CHECK ADD  CONSTRAINT [FK_KHACHO_Account] FOREIGN KEY([IDUser])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[HOPDONG_KHACHO] CHECK CONSTRAINT [FK_KHACHO_Account]
GO
ALTER TABLE [dbo].[HOPDONG_KHACHO]  WITH CHECK ADD  CONSTRAINT [FK_KHACHO_HopDong] FOREIGN KEY([IDHopDong])
REFERENCES [dbo].[HOPDONG] ([IDHopDong])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HOPDONG_KHACHO] CHECK CONSTRAINT [FK_KHACHO_HopDong]
GO
ALTER TABLE [dbo].[KHACH_THUE]  WITH CHECK ADD  CONSTRAINT [FK_KhachThue_Account] FOREIGN KEY([IDUser])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[KHACH_THUE] CHECK CONSTRAINT [FK_KhachThue_Account]
GO
ALTER TABLE [dbo].[PHONG_MANAGER]  WITH CHECK ADD FOREIGN KEY([IDManager])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
GO
ALTER TABLE [dbo].[PHONG_MANAGER]  WITH CHECK ADD FOREIGN KEY([IDPhong])
REFERENCES [dbo].[PHONG] ([IDPhong])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[THONGBAO]  WITH CHECK ADD FOREIGN KEY([IDUser])
REFERENCES [dbo].[ACCOUNT] ([IDUser])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD CHECK  (([Roles]='Tenant' OR [Roles]='Manager' OR [Roles]='Admin'))
GO
ALTER TABLE [dbo].[DONDV]  WITH CHECK ADD CHECK  (([LoaiDV]=N'Dịch vụ' OR [LoaiDV]=N'Hư hỏng' OR [LoaiDV]=N'Giặt sấy' OR [LoaiDV]=N'Nước bình'))
GO
ALTER TABLE [dbo].[DONDV]  WITH CHECK ADD CHECK  (([MucDo]=N'Khẩn cấp' OR [MucDo]=N'Trung bình' OR [MucDo]=N'Thấp'))
GO
ALTER TABLE [dbo].[DONDV]  WITH CHECK ADD  CONSTRAINT [CHK_DONDV_TrangThai_DV] CHECK  (([TrangThai_DV]=N'Lưu trữ' OR [TrangThai_DV]=N'Từ chối' OR [TrangThai_DV]=N'Đã hủy' OR [TrangThai_DV]=N'Đã hoàn thành' OR [TrangThai_DV]=N'Thành công' OR [TrangThai_DV]=N'Chờ duyệt' OR [TrangThai_DV]=N'Chờ thanh toán' OR [TrangThai_DV]=N'Đang xử lý' OR [TrangThai_DV]=N'Chờ xử lý'))
GO
ALTER TABLE [dbo].[DONDV] CHECK CONSTRAINT [CHK_DONDV_TrangThai_DV]
GO
ALTER TABLE [dbo].[HDTHANG]  WITH CHECK ADD CHECK  (([TrangThai_TT]=N'Quá hạn' OR [TrangThai_TT]=N'Đã hoàn thành' OR [TrangThai_TT]=N'Chờ duyệt' OR [TrangThai_TT]=N'Chưa đóng'))
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD CHECK  (([TrangThaiHD]=N'Đã hủy' OR [TrangThaiHD]=N'Đã kết thúc' OR [TrangThaiHD]=N'Đang hiệu lực'))
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD  CONSTRAINT [CK_HOPDONG_GiaThueChot] CHECK  (([GiaThueChot]>(0)))
GO
ALTER TABLE [dbo].[HOPDONG] CHECK CONSTRAINT [CK_HOPDONG_GiaThueChot]
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD  CONSTRAINT [CK_HOPDONG_NgayThanhLy] CHECK  (([NgayThanhLy] IS NULL OR [NgayThanhLy]>=[NgayBatDau]))
GO
ALTER TABLE [dbo].[HOPDONG] CHECK CONSTRAINT [CK_HOPDONG_NgayThanhLy]
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD  CONSTRAINT [CK_HOPDONG_TienCocHoanTra] CHECK  (([TienCocHoanTra] IS NULL OR [TienCocHoanTra]<=[TienCocBanDau]))
GO
ALTER TABLE [dbo].[HOPDONG] CHECK CONSTRAINT [CK_HOPDONG_TienCocHoanTra]
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU]  WITH CHECK ADD  CONSTRAINT [CK_HDDV_SoLuong] CHECK  (([SoLuong]>=(1)))
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU] CHECK CONSTRAINT [CK_HDDV_SoLuong]
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU]  WITH CHECK ADD  CONSTRAINT [CK_HDDV_TrangThai] CHECK  (([TrangThai]=N'Đã hủy' OR [TrangThai]=N'Đang dùng'))
GO
ALTER TABLE [dbo].[HOPDONG_DICHVU] CHECK CONSTRAINT [CK_HDDV_TrangThai]
GO
ALTER TABLE [dbo].[PHONG]  WITH CHECK ADD CHECK  (([TrangThai]=N'Đang sửa' OR [TrangThai]=N'Đã thuê' OR [TrangThai]=N'Trống'))
GO
ALTER TABLE [dbo].[THONGBAO]  WITH CHECK ADD CHECK  (([LoaiNguon]=NULL OR [LoaiNguon]='HeThong' OR [LoaiNguon]='DiemNuoc' OR [LoaiNguon]='HoaDon' OR [LoaiNguon]='DonDV'))
GO
ALTER TABLE [dbo].[THONGBAO]  WITH CHECK ADD CHECK  (([LoaiTB]=N'he-thong' OR [LoaiTB]=N'thanh-toan' OR [LoaiTB]=N'canh-bao' OR [LoaiTB]=N'thong-tin'))
GO
ALTER TABLE [dbo].[THONGKE_DOANHTHU_THANG]  WITH CHECK ADD CHECK  (([Thang]>=(1) AND [Thang]<=(12)))
GO
ALTER TABLE [dbo].[THONGKE_TONG]  WITH CHECK ADD  CONSTRAINT [CHK_ID_1] CHECK  (([ID]=(1)))
GO
ALTER TABLE [dbo].[THONGKE_TONG] CHECK CONSTRAINT [CHK_ID_1]
GO
/****** Object:  StoredProcedure [dbo].[SP_CapNhat_ThongKe_Tong]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- SP4: Cập nhật snapshot thống kê tổng (gọi sau mỗi transaction quan trọng)
CREATE   PROCEDURE [dbo].[SP_CapNhat_ThongKe_Tong]
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @KyHienTai VARCHAR(7) = FORMAT(GETDATE(), 'MM/yyyy');
    DECLARE @KyTruoc   VARCHAR(7) = FORMAT(DATEADD(MONTH, -1, GETDATE()), 'MM/yyyy');

    UPDATE THONGKE_TONG SET
        TongSoPhong         = (SELECT COUNT(*) FROM PHONG),
        PhongDangThue       = (SELECT COUNT(*) FROM PHONG WHERE TrangThai = N'Đã thuê'),
        PhongConTrong       = (SELECT COUNT(*) FROM PHONG WHERE TrangThai = N'Trống'),
        PhongDangSua        = (SELECT COUNT(*) FROM PHONG WHERE TrangThai = N'Đang sửa'),
        TiLeLapDay          = CAST(
                                (SELECT COUNT(*) FROM PHONG WHERE TrangThai = N'Đã thuê') * 100.0
                                / NULLIF((SELECT COUNT(*) FROM PHONG), 0)
                              AS DECIMAL(5,2)),
        DoanhThuThangNay    = ISNULL((SELECT SUM(TongCong) FROM HDTHANG
                                      WHERE KyThanhToan = @KyHienTai
                                        AND TrangThai_TT = N'Đã hoàn thành'), 0),
        DoanhThuThangTruoc  = ISNULL((SELECT SUM(TongCong) FROM HDTHANG
                                      WHERE KyThanhToan = @KyTruoc
                                        AND TrangThai_TT = N'Đã hoàn thành'), 0),
        TangTruongDoanhThu  = CASE
                                WHEN ISNULL((SELECT SUM(TongCong) FROM HDTHANG
                                             WHERE KyThanhToan = @KyTruoc
                                               AND TrangThai_TT = N'Đã hoàn thành'), 0) = 0
                                THEN 0
                                ELSE CAST(
                                    ((SELECT ISNULL(SUM(TongCong),0) FROM HDTHANG
                                       WHERE KyThanhToan = @KyHienTai
                                         AND TrangThai_TT = N'Đã hoàn thành')
                                     - (SELECT ISNULL(SUM(TongCong),0) FROM HDTHANG
                                        WHERE KyThanhToan = @KyTruoc
                                          AND TrangThai_TT = N'Đã hoàn thành'))
                                    * 100.0
                                    / (SELECT ISNULL(SUM(TongCong),1) FROM HDTHANG
                                       WHERE KyThanhToan = @KyTruoc
                                         AND TrangThai_TT = N'Đã hoàn thành')
                                AS DECIMAL(5,2))
                              END,
        HoaDonChuaDong      = (SELECT COUNT(*) FROM HDTHANG
                                WHERE TrangThai_TT = N'Chưa đóng'),
        HoaDonSapDenHan     = (SELECT COUNT(*) FROM HDTHANG
                                WHERE TrangThai_TT = N'Chưa đóng'
                                  AND HanDong BETWEEN CAST(GETDATE() AS DATE)
                                                  AND DATEADD(DAY, 7, CAST(GETDATE() AS DATE))),
        HoaDonQuaHan        = (SELECT COUNT(*) FROM HDTHANG
                                WHERE TrangThai_TT = N'Chưa đóng'
                                  AND HanDong < CAST(GETDATE() AS DATE)),
        DonDVChoXuLy        = (SELECT COUNT(*) FROM DONDV WHERE TrangThai_DV = N'Chờ xử lý'),
        DonDVKhanCap        = (SELECT COUNT(*) FROM DONDV
                                WHERE TrangThai_DV = N'Chờ xử lý'
                                  AND MucDo = N'Khẩn cấp'),
        NgayCapNhat         = SYSUTCDATETIME()
    WHERE ID = 1;
END;
GO
/****** Object:  StoredProcedure [dbo].[SP_ChiTiet_Phong]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- SP2: Chi tiết phòng đầy đủ (ChiTietPhong.cshtml)
CREATE   PROCEDURE [dbo].[SP_ChiTiet_Phong]
    @IDPhong INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Thông tin phòng + tenant hiện tại
    SELECT
        p.*,
        a.FullName   AS TenKhach,
        a.Phone      AS SdtKhach,
        a.Email      AS EmailKhach,
        hd.NgayBatDau, hd.NgayKetThuc,
        hd.TienCocBanDau,
        -- Manager phụ trách
        mgr.FullName AS TenManager,
        mgr.Phone    AS SdtManager
    FROM PHONG p
    LEFT JOIN HOPDONG hd   ON hd.IDPhong = p.IDPhong AND hd.TrangThaiHD = N'Đang hiệu lực'
    LEFT JOIN ACCOUNT a    ON a.IDUser = hd.IDUser
    LEFT JOIN PHONG_MANAGER pm ON pm.IDPhong = p.IDPhong AND pm.IsActive = 1
    LEFT JOIN ACCOUNT mgr  ON mgr.IDUser = pm.IDManager
    WHERE p.IDPhong = @IDPhong;

    -- 6 kỳ điện nước gần nhất
    SELECT TOP 6 * FROM DIENNUOC
    WHERE IDPhong = @IDPhong
    ORDER BY KyGhiNhan DESC;

    -- 6 hóa đơn gần nhất
    SELECT TOP 6 * FROM HDTHANG
    WHERE IDPhong = @IDPhong
    ORDER BY KyThanhToan DESC;

    -- Đơn DV chưa hoàn thành của phòng
    SELECT d.*, a.FullName AS TenKhach
    FROM DONDV d
    INNER JOIN ACCOUNT a ON a.IDUser = d.IDUser
    WHERE d.IDPhong = @IDPhong
      AND d.TrangThai_DV NOT IN (N'Thành công', N'Đã hủy')
    ORDER BY d.NgayTao DESC;
END;
GO
/****** Object:  StoredProcedure [dbo].[SP_Manager_Dashboard]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[SP_Manager_Dashboard]
    @IDManager INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Danh sách phòng được phân công
    SELECT
        p.IDPhong, p.SoPhong, p.Tang, p.TrangThai, p.GiaPhongFix,
        hd.IDUser      AS IDTenant,
        a.FullName     AS TenKhach,
        a.Phone        AS SdtKhach,
        hd.NgayBatDau, hd.NgayKetThuc,
        -- hóa đơn tháng hiện tại
        ht.TrangThai_TT AS TrangThaiHoaDon,
        ht.TongCong,
        ht.HanDong,
        -- đơn DV chờ xử lý
        (SELECT COUNT(*) FROM DONDV d
         WHERE d.IDPhong = p.IDPhong
           AND d.TrangThai_DV = N'Chờ xử lý') AS SoDonChoXuLy
    FROM PHONG_MANAGER pm
    INNER JOIN PHONG p ON p.IDPhong = pm.IDPhong
    LEFT JOIN HOPDONG hd ON hd.IDPhong = p.IDPhong
                         AND hd.TrangThaiHD = N'Đang hiệu lực'
    LEFT JOIN ACCOUNT a  ON a.IDUser = hd.IDUser
    LEFT JOIN HDTHANG ht ON ht.IDPhong = p.IDPhong
                         AND ht.KyThanhToan = FORMAT(GETDATE(), 'MM/yyyy')
    WHERE pm.IDManager = @IDManager
      AND pm.IsActive   = 1
    ORDER BY p.Tang, p.SoPhong;
END;
GO
/****** Object:  StoredProcedure [dbo].[SP_Manager_DonDV]    Script Date: 01/06/2026 10:59:04 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- SP3: Lấy đơn DV cho Manager (lọc theo phòng được giao + trạng thái)
CREATE   PROCEDURE [dbo].[SP_Manager_DonDV]
    @IDManager  INT,
    @TrangThai  NVARCHAR(30)  = NULL,   -- NULL = tất cả
    @LoaiDV     NVARCHAR(30)  = NULL,   -- NULL = tất cả
    @PageNumber INT           = 1,
    @PageSize   INT           = 20
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        dv.IDDonDV, dv.LoaiDV, dv.NoiDung, dv.MucDo,
        dv.TrangThai_DV, dv.TongTien, dv.NgayTao,
        dv.GhiChuXuLy, dv.NgayXuLy,
        a.FullName  AS TenKhach,
        a.Phone     AS SdtKhach,
        p.SoPhong
    FROM DONDV dv
    INNER JOIN ACCOUNT a ON a.IDUser  = dv.IDUser
    INNER JOIN PHONG   p ON p.IDPhong = dv.IDPhong
    INNER JOIN PHONG_MANAGER pm ON pm.IDPhong   = dv.IDPhong
                                AND pm.IDManager = @IDManager
                                AND pm.IsActive  = 1
    WHERE (@TrangThai IS NULL OR dv.TrangThai_DV = @TrangThai)
      AND (@LoaiDV    IS NULL OR dv.LoaiDV       = @LoaiDV)
    ORDER BY
        CASE dv.MucDo WHEN N'Khẩn cấp' THEN 1 WHEN N'Trung bình' THEN 2 ELSE 3 END,
        dv.NgayTao DESC
    OFFSET (@PageNumber - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY;
END;
GO
USE [master]
GO
ALTER DATABASE [QUANLY_KHUTRO] SET  READ_WRITE 
GO
