// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaTro.Models;

#nullable disable

namespace QuanLyNhaTro.Migrations
{
    [DbContext(typeof(QuanLyKhuNhaTro))]
    [Migration("20260514025507_Fix_Column_Location_V2")]
    partial class Fix_Column_Location_V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhaTro.Models.ACCOUNT", b =>
                {
                    b.Property<int>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUser"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Passwords")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("QR_Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDUser");

                    b.HasIndex("IsActive");

                    b.HasIndex("Roles");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ACCOUNT");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.CONFIG_GIA", b =>
                {
                    b.Property<int>("IDConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDConfig"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("NgayApDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDConfig");

                    b.HasIndex("MaDichVu")
                        .IsUnique();

                    b.ToTable("CONFIG_GIA");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.DIENNUOC", b =>
                {
                    b.Property<int>("IDGhiNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDGhiNhan"));

                    b.Property<string>("AnhChupDongHo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuDuyet")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IDManagerDuyet")
                        .HasColumnType("int");

                    b.Property<int>("IDPhong")
                        .HasColumnType("int");

                    b.Property<string>("KyGhiNhan")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SoDienCu")
                        .HasColumnType("int");

                    b.Property<int>("SoDienMoi")
                        .HasColumnType("int");

                    b.Property<int>("SoNuocCu")
                        .HasColumnType("int");

                    b.Property<int>("SoNuocMoi")
                        .HasColumnType("int");

                    b.Property<byte>("TrangThaiDuyet")
                        .HasColumnType("tinyint");

                    b.HasKey("IDGhiNhan");

                    b.HasIndex("IDManagerDuyet");

                    b.HasIndex("TrangThaiDuyet");

                    b.HasIndex("IDPhong", "KyGhiNhan")
                        .IsUnique();

                    b.ToTable("DIENNUOC");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.DONDV", b =>
                {
                    b.Property<int>("IDDonDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDonDV"));

                    b.Property<string>("AnhBienLai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AnhKetQua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuXuLy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IDManagerXuLy")
                        .HasColumnType("int");

                    b.Property<int>("IDPhong")
                        .HasColumnType("int");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("LoaiDV")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiHuy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("TrangThai_DV")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IDDonDV");

                    b.HasIndex("IDManagerXuLy");

                    b.HasIndex("IDPhong");

                    b.HasIndex("IDUser");

                    b.HasIndex("LoaiDV");

                    b.HasIndex("TrangThai_DV");

                    b.HasIndex("IDPhong", "TrangThai_DV");

                    b.ToTable("DONDV");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HDTHANG", b =>
                {
                    b.Property<int>("IDHDThang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHDThang"));

                    b.Property<string>("AnhChuyenKhoan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("DaCoNhacNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("DuocCongVaoTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("GhiChuDuyet")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("HanDong")
                        .HasColumnType("date");

                    b.Property<int?>("IDDienNuoc")
                        .HasColumnType("int");

                    b.Property<int?>("IDManagerDuyet")
                        .HasColumnType("int");

                    b.Property<int>("IDPhong")
                        .HasColumnType("int");

                    b.Property<string>("KyThanhToan")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXuatHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("TienDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienDienSum")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TienNoDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienNuocSum")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TongCong")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("TrangThai_TT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IDHDThang");

                    b.HasIndex("IDDienNuoc");

                    b.HasIndex("IDManagerDuyet");

                    b.HasIndex("TrangThai_TT");

                    b.HasIndex("IDPhong", "KyThanhToan")
                        .IsUnique();

                    b.HasIndex("KyThanhToan", "TrangThai_TT");

                    b.ToTable("HDTHANG");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HOPDONG", b =>
                {
                    b.Property<int>("IDHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHopDong"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DienDauKy")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IDManager")
                        .HasColumnType("int");

                    b.Property<int>("IDPhong")
                        .HasColumnType("int");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("NuocDauKy")
                        .HasColumnType("int");

                    b.Property<decimal>("TienCocBanDau")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("TrangThaiHD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IDHopDong");

                    b.HasIndex("IDManager");

                    b.HasIndex("IDPhong");

                    b.HasIndex("IDUser");

                    b.HasIndex("TrangThaiHD");

                    b.ToTable("HOPDONG");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.KHACH_THUE", b =>
                {
                    b.Property<int>("IDKhachThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDKhachThue"));

                    b.Property<string>("AnhChanDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IDKhachThue");

                    b.HasIndex("IDUser");

                    b.ToTable("KHACH_THUE");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.PHONG", b =>
                {
                    b.Property<int>("IDPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPhong"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("DienTich")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("GiaPhongFix")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("Tang")
                        .HasColumnType("tinyint");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDPhong");

                    b.HasIndex("SoPhong")
                        .IsUnique();

                    b.HasIndex("TrangThai");

                    b.ToTable("PHONG");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.PHONG_MANAGER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IDManager")
                        .HasColumnType("int");

                    b.Property<int>("IDPhong")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ID");

                    b.HasIndex("IDManager");

                    b.HasIndex("IDPhong", "IDManager", "IsActive")
                        .IsUnique();

                    b.ToTable("PHONG_MANAGER");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.REFRESH_TOKEN", b =>
                {
                    b.Property<int>("IDToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDToken"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("IDToken");

                    b.HasIndex("IDUser");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("REFRESH_TOKEN");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.THONGBAO", b =>
                {
                    b.Property<int>("IDThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int?>("IDNguoiGui")
                        .HasColumnType("int");

                    b.Property<int?>("IDNguonTB")
                        .HasColumnType("int");

                    b.Property<int?>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNguon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiTB")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IDThongBao");

                    b.HasIndex("IDNguoiGui");

                    b.HasIndex("NgayTao");

                    b.HasIndex("IDUser", "DaDoc");

                    b.ToTable("THONGBAO");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.THONGKE_DOANHTHU_THANG", b =>
                {
                    b.Property<int>("IDThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDThongKe"));

                    b.Property<decimal>("ChiPhiThang")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<short>("Nam")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SoHoaDonDaDong")
                        .HasColumnType("int");

                    b.Property<byte>("Thang")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TongCong")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TongTienDV")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TongTienDien")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TongTienNuoc")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TongTienPhong")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("IDThongKe");

                    b.HasIndex("Nam", "Thang")
                        .IsUnique();

                    b.ToTable("THONGKE_DOANHTHU_THANG");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.THONGKE_TONG", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DoanhThuThangNay")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("DoanhThuThangTruoc")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("DonDVChoXuLy")
                        .HasColumnType("int");

                    b.Property<int>("DonDVKhanCap")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonChuaDong")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonQuaHan")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonSapDenHan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PhongConTrong")
                        .HasColumnType("int");

                    b.Property<int>("PhongDangSua")
                        .HasColumnType("int");

                    b.Property<int>("PhongDangThue")
                        .HasColumnType("int");

                    b.Property<decimal>("TangTruongDoanhThu")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TiLeLapDay")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("TongSoPhong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("THONGKE_TONG", t =>
                        {
                            t.HasCheckConstraint("CHK_ID_1", "[ID] = 1");
                        });

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DoanhThuThangNay = 0m,
                            DoanhThuThangTruoc = 0m,
                            DonDVChoXuLy = 0,
                            DonDVKhanCap = 0,
                            HoaDonChuaDong = 0,
                            HoaDonQuaHan = 0,
                            HoaDonSapDenHan = 0,
                            NgayCapNhat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhongConTrong = 0,
                            PhongDangSua = 0,
                            PhongDangThue = 0,
                            TangTruongDoanhThu = 0m,
                            TiLeLapDay = 0m,
                            TongSoPhong = 0
                        });
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.DIENNUOC", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "ManagerDuyet")
                        .WithMany("DienNuocDuyet")
                        .HasForeignKey("IDManagerDuyet")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyNhaTro.Models.PHONG", "Phong")
                        .WithMany("DanhSachDienNuoc")
                        .HasForeignKey("IDPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagerDuyet");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.DONDV", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "ManagerXuLy")
                        .WithMany("DonDVXuLy")
                        .HasForeignKey("IDManagerXuLy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyNhaTro.Models.PHONG", "Phong")
                        .WithMany("DonDVs")
                        .HasForeignKey("IDPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "Tenant")
                        .WithMany("DonDVGuiDi")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagerXuLy");

                    b.Navigation("Phong");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HDTHANG", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.DIENNUOC", "DienNuoc")
                        .WithMany("HoaDonThangs")
                        .HasForeignKey("IDDienNuoc")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "ManagerDuyet")
                        .WithMany("HoaDonDuyet")
                        .HasForeignKey("IDManagerDuyet")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyNhaTro.Models.PHONG", "Phong")
                        .WithMany("HoaDonThangs")
                        .HasForeignKey("IDPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DienNuoc");

                    b.Navigation("ManagerDuyet");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.HOPDONG", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "Manager")
                        .WithMany("HopDongManagers")
                        .HasForeignKey("IDManager")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyNhaTro.Models.PHONG", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("IDPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "Tenant")
                        .WithMany("HopDongTenants")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Phong");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.KHACH_THUE", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "Account")
                        .WithMany("KhachThues")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.PHONG_MANAGER", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "Manager")
                        .WithMany("PhongManagers")
                        .HasForeignKey("IDManager")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyNhaTro.Models.PHONG", "Phong")
                        .WithMany("PhongManagers")
                        .HasForeignKey("IDPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.REFRESH_TOKEN", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.THONGBAO", b =>
                {
                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("IDNguoiGui")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyNhaTro.Models.ACCOUNT", "NguoiNhan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("IDUser")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.ACCOUNT", b =>
                {
                    b.Navigation("DienNuocDuyet");

                    b.Navigation("DonDVGuiDi");

                    b.Navigation("DonDVXuLy");

                    b.Navigation("HoaDonDuyet");

                    b.Navigation("HopDongManagers");

                    b.Navigation("HopDongTenants");

                    b.Navigation("KhachThues");

                    b.Navigation("PhongManagers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.DIENNUOC", b =>
                {
                    b.Navigation("HoaDonThangs");
                });

            modelBuilder.Entity("QuanLyNhaTro.Models.PHONG", b =>
                {
                    b.Navigation("DanhSachDienNuoc");

                    b.Navigation("DonDVs");

                    b.Navigation("HoaDonThangs");

                    b.Navigation("HopDongs");

                    b.Navigation("PhongManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
